version: '3'
services:
  app:
    build: './python'
    image: 'nfc_reader'
    container_name: 'reader'
    environment:
      TZ: Asia/Tokyo
    ports:
      - 5000:5000
    # to use USB device, privileged is required
    privileged: true
    volumes:
      - ./python/app:/app
  redis:
    image: redis:3.2.9
    container_name: 'redis'
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./storage/redis:/data
  # mysql:
  #   image: mysql:5.7
  #   container_name: 'mysql'
  #   environment:
  #     MYSQL_DATABASE: attendance
  #     MYSQL_USER: main
  #     MYSQL_PASSWORD: pass
  #     MYSQL_ROOT_PASSWORD: pass
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     # directory `./storage/mysql` must be empty or not exist on initialize
  #     - ./storage/mysql:/var/lib/mysql
  #     - ./mysql/:/etc/mysql/conf.d/
